api: add missing header for libc++ 14 after e2bf7b278d17
e2bf7b278d17In file included from plugins/single_plugins/place.cpp:1:
In file included from src/api/wayfire/signal-provider.hpp:7:
src/api/wayfire/nonstd/safe-list.hpp:144:35: error: implicit instantiation of undefined template 'std::vector<std::optional<wf::signal::connection_base_t *>>'
    std::vector<std::optional<T>> list;
                                  ^
src/api/wayfire/signal-provider.hpp:148:36: note: in instantiation of template class 'wf::safe_list_t<wf::signal::connection_base_t *>' requested here
        for (auto& [id, connected] : typed_connections)
                                   ^
/usr/include/c++/v1/iosfwd:260:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^